# -*- coding: utf-8 -*-
"""Python Functions used in the Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDnfRFfkW4dKGsLy8FDqll3jORKRnAVm
"""

## Only 1 function was used in the analysis of this project.

# Define a function to categorize age
def categorize_age(age):
    if 17 <= age <= 34:
        return '17-34'
    elif 35 <= age <= 50:
        return '35-50'
    elif 51 <= age <= 60:
        return '51-60'
    elif age >= 61:
        return '61+'
    else:
        return 'Unknown'